#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.NoobCryptStore.DA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NoobcryptStore")]
	public partial class dbNoobCryptDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBanner(Banner instance);
    partial void UpdateBanner(Banner instance);
    partial void DeleteBanner(Banner instance);
    partial void InsertVentaDetalle(VentaDetalle instance);
    partial void UpdateVentaDetalle(VentaDetalle instance);
    partial void DeleteVentaDetalle(VentaDetalle instance);
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertContacto(Contacto instance);
    partial void UpdateContacto(Contacto instance);
    partial void DeleteContacto(Contacto instance);
    partial void InsertDespacho(Despacho instance);
    partial void UpdateDespacho(Despacho instance);
    partial void DeleteDespacho(Despacho instance);
    partial void InsertDistrito(Distrito instance);
    partial void UpdateDistrito(Distrito instance);
    partial void DeleteDistrito(Distrito instance);
    partial void InsertInventario(Inventario instance);
    partial void UpdateInventario(Inventario instance);
    partial void DeleteInventario(Inventario instance);
    partial void InsertOferta(Oferta instance);
    partial void UpdateOferta(Oferta instance);
    partial void DeleteOferta(Oferta instance);
    partial void InsertOfertaDetalle(OfertaDetalle instance);
    partial void UpdateOfertaDetalle(OfertaDetalle instance);
    partial void DeleteOfertaDetalle(OfertaDetalle instance);
    partial void InsertPathFile(PathFile instance);
    partial void UpdatePathFile(PathFile instance);
    partial void DeletePathFile(PathFile instance);
    partial void InsertPersona(Persona instance);
    partial void UpdatePersona(Persona instance);
    partial void DeletePersona(Persona instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertTipoComprobante(TipoComprobante instance);
    partial void UpdateTipoComprobante(TipoComprobante instance);
    partial void DeleteTipoComprobante(TipoComprobante instance);
    partial void InsertTipoMovimiento(TipoMovimiento instance);
    partial void UpdateTipoMovimiento(TipoMovimiento instance);
    partial void DeleteTipoMovimiento(TipoMovimiento instance);
    partial void InsertVenta(Venta instance);
    partial void UpdateVenta(Venta instance);
    partial void DeleteVenta(Venta instance);
    #endregion
		
		public dbNoobCryptDataContext() : 
				base(global::UPC.NoobCryptStore.DA.Properties.Settings.Default.NoobcryptStoreConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbNoobCryptDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNoobCryptDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNoobCryptDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNoobCryptDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Banner> Banners
		{
			get
			{
				return this.GetTable<Banner>();
			}
		}
		
		public System.Data.Linq.Table<VentaDetalle> VentaDetalles
		{
			get
			{
				return this.GetTable<VentaDetalle>();
			}
		}
		
		public System.Data.Linq.Table<Categoria> Categorias
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Contacto> Contactos
		{
			get
			{
				return this.GetTable<Contacto>();
			}
		}
		
		public System.Data.Linq.Table<Despacho> Despachos
		{
			get
			{
				return this.GetTable<Despacho>();
			}
		}
		
		public System.Data.Linq.Table<Distrito> Distritos
		{
			get
			{
				return this.GetTable<Distrito>();
			}
		}
		
		public System.Data.Linq.Table<Inventario> Inventarios
		{
			get
			{
				return this.GetTable<Inventario>();
			}
		}
		
		public System.Data.Linq.Table<Membresia> Membresias
		{
			get
			{
				return this.GetTable<Membresia>();
			}
		}
		
		public System.Data.Linq.Table<Oferta> Ofertas
		{
			get
			{
				return this.GetTable<Oferta>();
			}
		}
		
		public System.Data.Linq.Table<OfertaDetalle> OfertaDetalles
		{
			get
			{
				return this.GetTable<OfertaDetalle>();
			}
		}
		
		public System.Data.Linq.Table<PathFile> PathFiles
		{
			get
			{
				return this.GetTable<PathFile>();
			}
		}
		
		public System.Data.Linq.Table<Persona> Personas
		{
			get
			{
				return this.GetTable<Persona>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Productos
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<TipoComprobante> TipoComprobantes
		{
			get
			{
				return this.GetTable<TipoComprobante>();
			}
		}
		
		public System.Data.Linq.Table<TipoMovimiento> TipoMovimientos
		{
			get
			{
				return this.GetTable<TipoMovimiento>();
			}
		}
		
		public System.Data.Linq.Table<tmpStock> tmpStocks
		{
			get
			{
				return this.GetTable<tmpStock>();
			}
		}
		
		public System.Data.Linq.Table<Venta> Ventas
		{
			get
			{
				return this.GetTable<Venta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Banner")]
	public partial class Banner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idPath;
		
		private string _nombre;
		
		private string _image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidPathChanging(int value);
    partial void OnidPathChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    #endregion
		
		public Banner()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPath", DbType="Int NOT NULL")]
		public int idPath
		{
			get
			{
				return this._idPath;
			}
			set
			{
				if ((this._idPath != value))
				{
					this.OnidPathChanging(value);
					this.SendPropertyChanging();
					this._idPath = value;
					this.SendPropertyChanged("idPath");
					this.OnidPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VentaDetalle")]
	public partial class VentaDetalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idVentaDeta;
		
		private long _idVenta;
		
		private int _idProducto;
		
		private decimal _cantidad;
		
		private decimal _costoUnitario;
		
		private decimal _costoTotal;
		
		private EntityRef<Producto> _Producto;
		
		private EntityRef<Venta> _Venta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidVentaDetaChanging(long value);
    partial void OnidVentaDetaChanged();
    partial void OnidVentaChanging(long value);
    partial void OnidVentaChanged();
    partial void OnidProductoChanging(int value);
    partial void OnidProductoChanged();
    partial void OncantidadChanging(decimal value);
    partial void OncantidadChanged();
    partial void OncostoUnitarioChanging(decimal value);
    partial void OncostoUnitarioChanged();
    partial void OncostoTotalChanging(decimal value);
    partial void OncostoTotalChanged();
    #endregion
		
		public VentaDetalle()
		{
			this._Producto = default(EntityRef<Producto>);
			this._Venta = default(EntityRef<Venta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVentaDeta", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long idVentaDeta
		{
			get
			{
				return this._idVentaDeta;
			}
			set
			{
				if ((this._idVentaDeta != value))
				{
					this.OnidVentaDetaChanging(value);
					this.SendPropertyChanging();
					this._idVentaDeta = value;
					this.SendPropertyChanged("idVentaDeta");
					this.OnidVentaDetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVenta", DbType="BigInt NOT NULL")]
		public long idVenta
		{
			get
			{
				return this._idVenta;
			}
			set
			{
				if ((this._idVenta != value))
				{
					if (this._Venta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidVentaChanging(value);
					this.SendPropertyChanging();
					this._idVenta = value;
					this.SendPropertyChanged("idVenta");
					this.OnidVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProductoChanging(value);
					this.SendPropertyChanging();
					this._idProducto = value;
					this.SendPropertyChanged("idProducto");
					this.OnidProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Decimal(10,3) NOT NULL")]
		public decimal cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costoUnitario", DbType="Decimal(10,2) NOT NULL")]
		public decimal costoUnitario
		{
			get
			{
				return this._costoUnitario;
			}
			set
			{
				if ((this._costoUnitario != value))
				{
					this.OncostoUnitarioChanging(value);
					this.SendPropertyChanging();
					this._costoUnitario = value;
					this.SendPropertyChanged("costoUnitario");
					this.OncostoUnitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costoTotal", DbType="Decimal(10,2) NOT NULL")]
		public decimal costoTotal
		{
			get
			{
				return this._costoTotal;
			}
			set
			{
				if ((this._costoTotal != value))
				{
					this.OncostoTotalChanging(value);
					this.SendPropertyChanging();
					this._costoTotal = value;
					this.SendPropertyChanged("costoTotal");
					this.OncostoTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_VentaDetalle", Storage="_Producto", ThisKey="idProducto", OtherKey="idProducto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.VentaDetalles.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.VentaDetalles.Add(this);
						this._idProducto = value.idProducto;
					}
					else
					{
						this._idProducto = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venta_VentaDetalle", Storage="_Venta", ThisKey="idVenta", OtherKey="idVenta", IsForeignKey=true)]
		public Venta Venta
		{
			get
			{
				return this._Venta.Entity;
			}
			set
			{
				Venta previousValue = this._Venta.Entity;
				if (((previousValue != value) 
							|| (this._Venta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Venta.Entity = null;
						previousValue.VentaDetalles.Remove(this);
					}
					this._Venta.Entity = value;
					if ((value != null))
					{
						value.VentaDetalles.Add(this);
						this._idVenta = value.idVenta;
					}
					else
					{
						this._idVenta = default(long);
					}
					this.SendPropertyChanged("Venta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCategoria;
		
		private string _descripcion;
		
		private string _image;
		
		private string _detalle;
		
		private EntitySet<Producto> _Productos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCategoriaChanging(int value);
    partial void OnidCategoriaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OndetalleChanging(string value);
    partial void OndetalleChanged();
    #endregion
		
		public Categoria()
		{
			this._Productos = new EntitySet<Producto>(new Action<Producto>(this.attach_Productos), new Action<Producto>(this.detach_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this.OnidCategoriaChanging(value);
					this.SendPropertyChanging();
					this._idCategoria = value;
					this.SendPropertyChanged("idCategoria");
					this.OnidCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detalle", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string detalle
		{
			get
			{
				return this._detalle;
			}
			set
			{
				if ((this._detalle != value))
				{
					this.OndetalleChanging(value);
					this.SendPropertyChanging();
					this._detalle = value;
					this.SendPropertyChanged("detalle");
					this.OndetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Producto", Storage="_Productos", ThisKey="idCategoria", OtherKey="idCategoria")]
		public EntitySet<Producto> Productos
		{
			get
			{
				return this._Productos;
			}
			set
			{
				this._Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contacto")]
	public partial class Contacto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idContacto;
		
		private string _nombre;
		
		private string _email;
		
		private string _asunto;
		
		private string _mensaje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidContactoChanging(long value);
    partial void OnidContactoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnasuntoChanging(string value);
    partial void OnasuntoChanged();
    partial void OnmensajeChanging(string value);
    partial void OnmensajeChanged();
    #endregion
		
		public Contacto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idContacto", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long idContacto
		{
			get
			{
				return this._idContacto;
			}
			set
			{
				if ((this._idContacto != value))
				{
					this.OnidContactoChanging(value);
					this.SendPropertyChanging();
					this._idContacto = value;
					this.SendPropertyChanged("idContacto");
					this.OnidContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asunto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string asunto
		{
			get
			{
				return this._asunto;
			}
			set
			{
				if ((this._asunto != value))
				{
					this.OnasuntoChanging(value);
					this.SendPropertyChanging();
					this._asunto = value;
					this.SendPropertyChanged("asunto");
					this.OnasuntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this.OnmensajeChanging(value);
					this.SendPropertyChanging();
					this._mensaje = value;
					this.SendPropertyChanged("mensaje");
					this.OnmensajeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Despacho")]
	public partial class Despacho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDespacho;
		
		private string _descripcion;
		
		private EntitySet<Venta> _Ventas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDespachoChanging(int value);
    partial void OnidDespachoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Despacho()
		{
			this._Ventas = new EntitySet<Venta>(new Action<Venta>(this.attach_Ventas), new Action<Venta>(this.detach_Ventas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDespacho", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDespacho
		{
			get
			{
				return this._idDespacho;
			}
			set
			{
				if ((this._idDespacho != value))
				{
					this.OnidDespachoChanging(value);
					this.SendPropertyChanging();
					this._idDespacho = value;
					this.SendPropertyChanged("idDespacho");
					this.OnidDespachoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Despacho_Venta", Storage="_Ventas", ThisKey="idDespacho", OtherKey="idDespacho")]
		public EntitySet<Venta> Ventas
		{
			get
			{
				return this._Ventas;
			}
			set
			{
				this._Ventas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ventas(Venta entity)
		{
			this.SendPropertyChanging();
			entity.Despacho = this;
		}
		
		private void detach_Ventas(Venta entity)
		{
			this.SendPropertyChanging();
			entity.Despacho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Distrito")]
	public partial class Distrito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idDistrito;
		
		private string _Descripcion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDistritoChanging(string value);
    partial void OnidDistritoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public Distrito()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDistrito", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idDistrito
		{
			get
			{
				return this._idDistrito;
			}
			set
			{
				if ((this._idDistrito != value))
				{
					this.OnidDistritoChanging(value);
					this.SendPropertyChanging();
					this._idDistrito = value;
					this.SendPropertyChanged("idDistrito");
					this.OnidDistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inventario")]
	public partial class Inventario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idInventario;
		
		private System.DateTime _fechaMov;
		
		private int _idTipoMov;
		
		private char _flagMov;
		
		private int _idProducto;
		
		private decimal _cantidad;
		
		private char _condicion;
		
		private string _comprobante;
		
		private EntityRef<Producto> _Producto;
		
		private EntityRef<TipoMovimiento> _TipoMovimiento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidInventarioChanging(long value);
    partial void OnidInventarioChanged();
    partial void OnfechaMovChanging(System.DateTime value);
    partial void OnfechaMovChanged();
    partial void OnidTipoMovChanging(int value);
    partial void OnidTipoMovChanged();
    partial void OnflagMovChanging(char value);
    partial void OnflagMovChanged();
    partial void OnidProductoChanging(int value);
    partial void OnidProductoChanged();
    partial void OncantidadChanging(decimal value);
    partial void OncantidadChanged();
    partial void OncondicionChanging(char value);
    partial void OncondicionChanged();
    partial void OncomprobanteChanging(string value);
    partial void OncomprobanteChanged();
    #endregion
		
		public Inventario()
		{
			this._Producto = default(EntityRef<Producto>);
			this._TipoMovimiento = default(EntityRef<TipoMovimiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idInventario", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long idInventario
		{
			get
			{
				return this._idInventario;
			}
			set
			{
				if ((this._idInventario != value))
				{
					this.OnidInventarioChanging(value);
					this.SendPropertyChanging();
					this._idInventario = value;
					this.SendPropertyChanged("idInventario");
					this.OnidInventarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaMov", DbType="Date NOT NULL")]
		public System.DateTime fechaMov
		{
			get
			{
				return this._fechaMov;
			}
			set
			{
				if ((this._fechaMov != value))
				{
					this.OnfechaMovChanging(value);
					this.SendPropertyChanging();
					this._fechaMov = value;
					this.SendPropertyChanged("fechaMov");
					this.OnfechaMovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoMov", DbType="Int NOT NULL")]
		public int idTipoMov
		{
			get
			{
				return this._idTipoMov;
			}
			set
			{
				if ((this._idTipoMov != value))
				{
					if (this._TipoMovimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoMovChanging(value);
					this.SendPropertyChanging();
					this._idTipoMov = value;
					this.SendPropertyChanged("idTipoMov");
					this.OnidTipoMovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flagMov", DbType="Char(1) NOT NULL")]
		public char flagMov
		{
			get
			{
				return this._flagMov;
			}
			set
			{
				if ((this._flagMov != value))
				{
					this.OnflagMovChanging(value);
					this.SendPropertyChanging();
					this._flagMov = value;
					this.SendPropertyChanged("flagMov");
					this.OnflagMovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProductoChanging(value);
					this.SendPropertyChanging();
					this._idProducto = value;
					this.SendPropertyChanged("idProducto");
					this.OnidProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Decimal(10,3) NOT NULL")]
		public decimal cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_condicion", DbType="Char(1) NOT NULL")]
		public char condicion
		{
			get
			{
				return this._condicion;
			}
			set
			{
				if ((this._condicion != value))
				{
					this.OncondicionChanging(value);
					this.SendPropertyChanging();
					this._condicion = value;
					this.SendPropertyChanged("condicion");
					this.OncondicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comprobante", DbType="NVarChar(30)")]
		public string comprobante
		{
			get
			{
				return this._comprobante;
			}
			set
			{
				if ((this._comprobante != value))
				{
					this.OncomprobanteChanging(value);
					this.SendPropertyChanging();
					this._comprobante = value;
					this.SendPropertyChanged("comprobante");
					this.OncomprobanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Inventario", Storage="_Producto", ThisKey="idProducto", OtherKey="idProducto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Inventarios.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Inventarios.Add(this);
						this._idProducto = value.idProducto;
					}
					else
					{
						this._idProducto = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoMovimiento_Inventario", Storage="_TipoMovimiento", ThisKey="idTipoMov", OtherKey="idTipoMov", IsForeignKey=true)]
		public TipoMovimiento TipoMovimiento
		{
			get
			{
				return this._TipoMovimiento.Entity;
			}
			set
			{
				TipoMovimiento previousValue = this._TipoMovimiento.Entity;
				if (((previousValue != value) 
							|| (this._TipoMovimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoMovimiento.Entity = null;
						previousValue.Inventarios.Remove(this);
					}
					this._TipoMovimiento.Entity = value;
					if ((value != null))
					{
						value.Inventarios.Add(this);
						this._idTipoMov = value.idTipoMov;
					}
					else
					{
						this._idTipoMov = default(int);
					}
					this.SendPropertyChanged("TipoMovimiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Membresia")]
	public partial class Membresia
	{
		
		private string _IdSocio;
		
		private System.Nullable<int> _Membresia1;
		
		private System.Nullable<int> _Periodo;
		
		public Membresia()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSocio", DbType="VarChar(50)")]
		public string IdSocio
		{
			get
			{
				return this._IdSocio;
			}
			set
			{
				if ((this._IdSocio != value))
				{
					this._IdSocio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Membresia", Storage="_Membresia1", DbType="Int")]
		public System.Nullable<int> Membresia1
		{
			get
			{
				return this._Membresia1;
			}
			set
			{
				if ((this._Membresia1 != value))
				{
					this._Membresia1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Periodo", DbType="Int")]
		public System.Nullable<int> Periodo
		{
			get
			{
				return this._Periodo;
			}
			set
			{
				if ((this._Periodo != value))
				{
					this._Periodo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Oferta")]
	public partial class Oferta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idOferta;
		
		private string _descripcion;
		
		private decimal _costoOferta;
		
		private bool _vigencia;
		
		private int _idUsuario;
		
		private EntitySet<OfertaDetalle> _OfertaDetalles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidOfertaChanging(int value);
    partial void OnidOfertaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OncostoOfertaChanging(decimal value);
    partial void OncostoOfertaChanged();
    partial void OnvigenciaChanging(bool value);
    partial void OnvigenciaChanged();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    #endregion
		
		public Oferta()
		{
			this._OfertaDetalles = new EntitySet<OfertaDetalle>(new Action<OfertaDetalle>(this.attach_OfertaDetalles), new Action<OfertaDetalle>(this.detach_OfertaDetalles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOferta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idOferta
		{
			get
			{
				return this._idOferta;
			}
			set
			{
				if ((this._idOferta != value))
				{
					this.OnidOfertaChanging(value);
					this.SendPropertyChanging();
					this._idOferta = value;
					this.SendPropertyChanged("idOferta");
					this.OnidOfertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costoOferta", DbType="Decimal(10,2) NOT NULL")]
		public decimal costoOferta
		{
			get
			{
				return this._costoOferta;
			}
			set
			{
				if ((this._costoOferta != value))
				{
					this.OncostoOfertaChanging(value);
					this.SendPropertyChanging();
					this._costoOferta = value;
					this.SendPropertyChanged("costoOferta");
					this.OncostoOfertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigencia", DbType="Bit NOT NULL")]
		public bool vigencia
		{
			get
			{
				return this._vigencia;
			}
			set
			{
				if ((this._vigencia != value))
				{
					this.OnvigenciaChanging(value);
					this.SendPropertyChanging();
					this._vigencia = value;
					this.SendPropertyChanged("vigencia");
					this.OnvigenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Oferta_OfertaDetalle", Storage="_OfertaDetalles", ThisKey="idOferta", OtherKey="idOferta")]
		public EntitySet<OfertaDetalle> OfertaDetalles
		{
			get
			{
				return this._OfertaDetalles;
			}
			set
			{
				this._OfertaDetalles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OfertaDetalles(OfertaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.Oferta = this;
		}
		
		private void detach_OfertaDetalles(OfertaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.Oferta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OfertaDetalle")]
	public partial class OfertaDetalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idOfertaDeta;
		
		private int _idOferta;
		
		private int _IdProducto;
		
		private decimal _cantidad;
		
		private decimal _costoUnitario;
		
		private decimal _costoTotal;
		
		private EntityRef<Oferta> _Oferta;
		
		private EntityRef<Producto> _Producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidOfertaDetaChanging(long value);
    partial void OnidOfertaDetaChanged();
    partial void OnidOfertaChanging(int value);
    partial void OnidOfertaChanged();
    partial void OnIdProductoChanging(int value);
    partial void OnIdProductoChanged();
    partial void OncantidadChanging(decimal value);
    partial void OncantidadChanged();
    partial void OncostoUnitarioChanging(decimal value);
    partial void OncostoUnitarioChanged();
    partial void OncostoTotalChanging(decimal value);
    partial void OncostoTotalChanged();
    #endregion
		
		public OfertaDetalle()
		{
			this._Oferta = default(EntityRef<Oferta>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOfertaDeta", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long idOfertaDeta
		{
			get
			{
				return this._idOfertaDeta;
			}
			set
			{
				if ((this._idOfertaDeta != value))
				{
					this.OnidOfertaDetaChanging(value);
					this.SendPropertyChanging();
					this._idOfertaDeta = value;
					this.SendPropertyChanged("idOfertaDeta");
					this.OnidOfertaDetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOferta", DbType="Int NOT NULL")]
		public int idOferta
		{
			get
			{
				return this._idOferta;
			}
			set
			{
				if ((this._idOferta != value))
				{
					if (this._Oferta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidOfertaChanging(value);
					this.SendPropertyChanging();
					this._idOferta = value;
					this.SendPropertyChanged("idOferta");
					this.OnidOfertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProductoChanging(value);
					this.SendPropertyChanging();
					this._IdProducto = value;
					this.SendPropertyChanged("IdProducto");
					this.OnIdProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Decimal(10,3) NOT NULL")]
		public decimal cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costoUnitario", DbType="Decimal(10,2) NOT NULL")]
		public decimal costoUnitario
		{
			get
			{
				return this._costoUnitario;
			}
			set
			{
				if ((this._costoUnitario != value))
				{
					this.OncostoUnitarioChanging(value);
					this.SendPropertyChanging();
					this._costoUnitario = value;
					this.SendPropertyChanged("costoUnitario");
					this.OncostoUnitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costoTotal", DbType="Decimal(10,2) NOT NULL")]
		public decimal costoTotal
		{
			get
			{
				return this._costoTotal;
			}
			set
			{
				if ((this._costoTotal != value))
				{
					this.OncostoTotalChanging(value);
					this.SendPropertyChanging();
					this._costoTotal = value;
					this.SendPropertyChanged("costoTotal");
					this.OncostoTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Oferta_OfertaDetalle", Storage="_Oferta", ThisKey="idOferta", OtherKey="idOferta", IsForeignKey=true)]
		public Oferta Oferta
		{
			get
			{
				return this._Oferta.Entity;
			}
			set
			{
				Oferta previousValue = this._Oferta.Entity;
				if (((previousValue != value) 
							|| (this._Oferta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Oferta.Entity = null;
						previousValue.OfertaDetalles.Remove(this);
					}
					this._Oferta.Entity = value;
					if ((value != null))
					{
						value.OfertaDetalles.Add(this);
						this._idOferta = value.idOferta;
					}
					else
					{
						this._idOferta = default(int);
					}
					this.SendPropertyChanged("Oferta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_OfertaDetalle", Storage="_Producto", ThisKey="IdProducto", OtherKey="idProducto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.OfertaDetalles.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.OfertaDetalles.Add(this);
						this._IdProducto = value.idProducto;
					}
					else
					{
						this._IdProducto = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PathFile")]
	public partial class PathFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPath;
		
		private string _tipo;
		
		private string _descripcion;
		
		private string _ruta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPathChanging(int value);
    partial void OnidPathChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnrutaChanging(string value);
    partial void OnrutaChanged();
    #endregion
		
		public PathFile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPath", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPath
		{
			get
			{
				return this._idPath;
			}
			set
			{
				if ((this._idPath != value))
				{
					this.OnidPathChanging(value);
					this.SendPropertyChanging();
					this._idPath = value;
					this.SendPropertyChanged("idPath");
					this.OnidPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruta", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ruta
		{
			get
			{
				return this._ruta;
			}
			set
			{
				if ((this._ruta != value))
				{
					this.OnrutaChanging(value);
					this.SendPropertyChanging();
					this._ruta = value;
					this.SendPropertyChanged("ruta");
					this.OnrutaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persona")]
	public partial class Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPersona;
		
		private string _dni;
		
		private string _nombres;
		
		private string _apellidos;
		
		private System.Nullable<char> _sexo;
		
		private System.Nullable<System.DateTime> _nacimiento;
		
		private string _email;
		
		private string _celular;
		
		private string _idDistrito;
		
		private string _direccion;
		
		private string _referencia;
		
		private string _contraseña;
		
		private string _role;
		
		private EntitySet<Venta> _Ventas;
		
		private EntitySet<Venta> _Ventas1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPersonaChanging(int value);
    partial void OnidPersonaChanged();
    partial void OndniChanging(string value);
    partial void OndniChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnsexoChanging(System.Nullable<char> value);
    partial void OnsexoChanged();
    partial void OnnacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnnacimientoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OnidDistritoChanging(string value);
    partial void OnidDistritoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnreferenciaChanging(string value);
    partial void OnreferenciaChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    #endregion
		
		public Persona()
		{
			this._Ventas = new EntitySet<Venta>(new Action<Venta>(this.attach_Ventas), new Action<Venta>(this.detach_Ventas));
			this._Ventas1 = new EntitySet<Venta>(new Action<Venta>(this.attach_Ventas1), new Action<Venta>(this.detach_Ventas1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersona", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPersona
		{
			get
			{
				return this._idPersona;
			}
			set
			{
				if ((this._idPersona != value))
				{
					this.OnidPersonaChanging(value);
					this.SendPropertyChanging();
					this._idPersona = value;
					this.SendPropertyChanged("idPersona");
					this.OnidPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					this.OndniChanging(value);
					this.SendPropertyChanging();
					this._dni = value;
					this.SendPropertyChanged("dni");
					this.OndniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(80)")]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1)")]
		public System.Nullable<char> sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> nacimiento
		{
			get
			{
				return this._nacimiento;
			}
			set
			{
				if ((this._nacimiento != value))
				{
					this.OnnacimientoChanging(value);
					this.SendPropertyChanging();
					this._nacimiento = value;
					this.SendPropertyChanged("nacimiento");
					this.OnnacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="NVarChar(9)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDistrito", DbType="NVarChar(6)")]
		public string idDistrito
		{
			get
			{
				return this._idDistrito;
			}
			set
			{
				if ((this._idDistrito != value))
				{
					this.OnidDistritoChanging(value);
					this.SendPropertyChanging();
					this._idDistrito = value;
					this.SendPropertyChanged("idDistrito");
					this.OnidDistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(250)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia", DbType="VarChar(250)")]
		public string referencia
		{
			get
			{
				return this._referencia;
			}
			set
			{
				if ((this._referencia != value))
				{
					this.OnreferenciaChanging(value);
					this.SendPropertyChanging();
					this._referencia = value;
					this.SendPropertyChanged("referencia");
					this.OnreferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(900) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Venta", Storage="_Ventas", ThisKey="idPersona", OtherKey="idCliente")]
		public EntitySet<Venta> Ventas
		{
			get
			{
				return this._Ventas;
			}
			set
			{
				this._Ventas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Venta1", Storage="_Ventas1", ThisKey="idPersona", OtherKey="idVendedor")]
		public EntitySet<Venta> Ventas1
		{
			get
			{
				return this._Ventas1;
			}
			set
			{
				this._Ventas1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ventas(Venta entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Ventas(Venta entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Ventas1(Venta entity)
		{
			this.SendPropertyChanging();
			entity.Persona1 = this;
		}
		
		private void detach_Ventas1(Venta entity)
		{
			this.SendPropertyChanging();
			entity.Persona1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProducto;
		
		private string _codigoProducto;
		
		private int _idCategoria;
		
		private string _nombreProducto;
		
		private decimal _precioBase;
		
		private int _stockMinimo;
		
		private int _idUsuario;
		
		private string _imageFile;
		
		private EntitySet<VentaDetalle> _VentaDetalles;
		
		private EntitySet<Inventario> _Inventarios;
		
		private EntitySet<OfertaDetalle> _OfertaDetalles;
		
		private EntityRef<Categoria> _Categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProductoChanging(int value);
    partial void OnidProductoChanged();
    partial void OncodigoProductoChanging(string value);
    partial void OncodigoProductoChanged();
    partial void OnidCategoriaChanging(int value);
    partial void OnidCategoriaChanged();
    partial void OnnombreProductoChanging(string value);
    partial void OnnombreProductoChanged();
    partial void OnprecioBaseChanging(decimal value);
    partial void OnprecioBaseChanged();
    partial void OnstockMinimoChanging(int value);
    partial void OnstockMinimoChanged();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnimageFileChanging(string value);
    partial void OnimageFileChanged();
    #endregion
		
		public Producto()
		{
			this._VentaDetalles = new EntitySet<VentaDetalle>(new Action<VentaDetalle>(this.attach_VentaDetalles), new Action<VentaDetalle>(this.detach_VentaDetalles));
			this._Inventarios = new EntitySet<Inventario>(new Action<Inventario>(this.attach_Inventarios), new Action<Inventario>(this.detach_Inventarios));
			this._OfertaDetalles = new EntitySet<OfertaDetalle>(new Action<OfertaDetalle>(this.attach_OfertaDetalles), new Action<OfertaDetalle>(this.detach_OfertaDetalles));
			this._Categoria = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this.OnidProductoChanging(value);
					this.SendPropertyChanging();
					this._idProducto = value;
					this.SendPropertyChanged("idProducto");
					this.OnidProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this.OncodigoProductoChanging(value);
					this.SendPropertyChanging();
					this._codigoProducto = value;
					this.SendPropertyChanged("codigoProducto");
					this.OncodigoProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL")]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					if (this._Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCategoriaChanging(value);
					this.SendPropertyChanging();
					this._idCategoria = value;
					this.SendPropertyChanged("idCategoria");
					this.OnidCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this.OnnombreProductoChanging(value);
					this.SendPropertyChanging();
					this._nombreProducto = value;
					this.SendPropertyChanged("nombreProducto");
					this.OnnombreProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioBase", DbType="Decimal(10,2) NOT NULL")]
		public decimal precioBase
		{
			get
			{
				return this._precioBase;
			}
			set
			{
				if ((this._precioBase != value))
				{
					this.OnprecioBaseChanging(value);
					this.SendPropertyChanging();
					this._precioBase = value;
					this.SendPropertyChanged("precioBase");
					this.OnprecioBaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stockMinimo", DbType="Int NOT NULL")]
		public int stockMinimo
		{
			get
			{
				return this._stockMinimo;
			}
			set
			{
				if ((this._stockMinimo != value))
				{
					this.OnstockMinimoChanging(value);
					this.SendPropertyChanging();
					this._stockMinimo = value;
					this.SendPropertyChanged("stockMinimo");
					this.OnstockMinimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageFile", DbType="NVarChar(MAX)")]
		public string imageFile
		{
			get
			{
				return this._imageFile;
			}
			set
			{
				if ((this._imageFile != value))
				{
					this.OnimageFileChanging(value);
					this.SendPropertyChanging();
					this._imageFile = value;
					this.SendPropertyChanged("imageFile");
					this.OnimageFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_VentaDetalle", Storage="_VentaDetalles", ThisKey="idProducto", OtherKey="idProducto")]
		public EntitySet<VentaDetalle> VentaDetalles
		{
			get
			{
				return this._VentaDetalles;
			}
			set
			{
				this._VentaDetalles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Inventario", Storage="_Inventarios", ThisKey="idProducto", OtherKey="idProducto")]
		public EntitySet<Inventario> Inventarios
		{
			get
			{
				return this._Inventarios;
			}
			set
			{
				this._Inventarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_OfertaDetalle", Storage="_OfertaDetalles", ThisKey="idProducto", OtherKey="IdProducto")]
		public EntitySet<OfertaDetalle> OfertaDetalles
		{
			get
			{
				return this._OfertaDetalles;
			}
			set
			{
				this._OfertaDetalles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Producto", Storage="_Categoria", ThisKey="idCategoria", OtherKey="idCategoria", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Productos.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Productos.Add(this);
						this._idCategoria = value.idCategoria;
					}
					else
					{
						this._idCategoria = default(int);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VentaDetalles(VentaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_VentaDetalles(VentaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Inventarios(Inventario entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Inventarios(Inventario entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_OfertaDetalles(OfertaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_OfertaDetalles(OfertaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoComprobante")]
	public partial class TipoComprobante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipoComp;
		
		private string _descripcion;
		
		private string _nomenclatura;
		
		private EntitySet<Venta> _Ventas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoCompChanging(int value);
    partial void OnidTipoCompChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnnomenclaturaChanging(string value);
    partial void OnnomenclaturaChanged();
    #endregion
		
		public TipoComprobante()
		{
			this._Ventas = new EntitySet<Venta>(new Action<Venta>(this.attach_Ventas), new Action<Venta>(this.detach_Ventas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoComp", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipoComp
		{
			get
			{
				return this._idTipoComp;
			}
			set
			{
				if ((this._idTipoComp != value))
				{
					this.OnidTipoCompChanging(value);
					this.SendPropertyChanging();
					this._idTipoComp = value;
					this.SendPropertyChanged("idTipoComp");
					this.OnidTipoCompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomenclatura", DbType="VarChar(2)")]
		public string nomenclatura
		{
			get
			{
				return this._nomenclatura;
			}
			set
			{
				if ((this._nomenclatura != value))
				{
					this.OnnomenclaturaChanging(value);
					this.SendPropertyChanging();
					this._nomenclatura = value;
					this.SendPropertyChanged("nomenclatura");
					this.OnnomenclaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoComprobante_Venta", Storage="_Ventas", ThisKey="idTipoComp", OtherKey="idTipoComp")]
		public EntitySet<Venta> Ventas
		{
			get
			{
				return this._Ventas;
			}
			set
			{
				this._Ventas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ventas(Venta entity)
		{
			this.SendPropertyChanging();
			entity.TipoComprobante = this;
		}
		
		private void detach_Ventas(Venta entity)
		{
			this.SendPropertyChanging();
			entity.TipoComprobante = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoMovimiento")]
	public partial class TipoMovimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipoMov;
		
		private string _descripcion;
		
		private EntitySet<Inventario> _Inventarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoMovChanging(int value);
    partial void OnidTipoMovChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public TipoMovimiento()
		{
			this._Inventarios = new EntitySet<Inventario>(new Action<Inventario>(this.attach_Inventarios), new Action<Inventario>(this.detach_Inventarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoMov", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipoMov
		{
			get
			{
				return this._idTipoMov;
			}
			set
			{
				if ((this._idTipoMov != value))
				{
					this.OnidTipoMovChanging(value);
					this.SendPropertyChanging();
					this._idTipoMov = value;
					this.SendPropertyChanged("idTipoMov");
					this.OnidTipoMovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(100)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoMovimiento_Inventario", Storage="_Inventarios", ThisKey="idTipoMov", OtherKey="idTipoMov")]
		public EntitySet<Inventario> Inventarios
		{
			get
			{
				return this._Inventarios;
			}
			set
			{
				this._Inventarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Inventarios(Inventario entity)
		{
			this.SendPropertyChanging();
			entity.TipoMovimiento = this;
		}
		
		private void detach_Inventarios(Inventario entity)
		{
			this.SendPropertyChanging();
			entity.TipoMovimiento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tmpStock")]
	public partial class tmpStock
	{
		
		private int _idProducto;
		
		private string _codigoProducto;
		
		private int _idCategoria;
		
		private string _nombreCategoria;
		
		private string _nombreProducto;
		
		private string _imageFile;
		
		private decimal _precioBase;
		
		private int _stockMinimo;
		
		private System.Nullable<decimal> _stock;
		
		public tmpStock()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL")]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this._idCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCategoria", DbType="VarChar(50)")]
		public string nombreCategoria
		{
			get
			{
				return this._nombreCategoria;
			}
			set
			{
				if ((this._nombreCategoria != value))
				{
					this._nombreCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this._nombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageFile", DbType="NVarChar(MAX)")]
		public string imageFile
		{
			get
			{
				return this._imageFile;
			}
			set
			{
				if ((this._imageFile != value))
				{
					this._imageFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioBase", DbType="Decimal(10,2) NOT NULL")]
		public decimal precioBase
		{
			get
			{
				return this._precioBase;
			}
			set
			{
				if ((this._precioBase != value))
				{
					this._precioBase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stockMinimo", DbType="Int NOT NULL")]
		public int stockMinimo
		{
			get
			{
				return this._stockMinimo;
			}
			set
			{
				if ((this._stockMinimo != value))
				{
					this._stockMinimo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock", DbType="Decimal(38,3)")]
		public System.Nullable<decimal> stock
		{
			get
			{
				return this._stock;
			}
			set
			{
				if ((this._stock != value))
				{
					this._stock = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Venta")]
	public partial class Venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idVenta;
		
		private System.DateTime _fechaVenta;
		
		private int _idTipoComp;
		
		private string _comprobante;
		
		private int _idCliente;
		
		private decimal _importeTotal;
		
		private int _idVendedor;
		
		private int _idDespacho;
		
		private int _idUsuario;
		
		private char _estado;
		
		private string _compAnterior;
		
		private EntitySet<VentaDetalle> _VentaDetalles;
		
		private EntityRef<Persona> _Persona;
		
		private EntityRef<Despacho> _Despacho;
		
		private EntityRef<TipoComprobante> _TipoComprobante;
		
		private EntityRef<Persona> _Persona1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidVentaChanging(long value);
    partial void OnidVentaChanged();
    partial void OnfechaVentaChanging(System.DateTime value);
    partial void OnfechaVentaChanged();
    partial void OnidTipoCompChanging(int value);
    partial void OnidTipoCompChanged();
    partial void OncomprobanteChanging(string value);
    partial void OncomprobanteChanged();
    partial void OnidClienteChanging(int value);
    partial void OnidClienteChanged();
    partial void OnimporteTotalChanging(decimal value);
    partial void OnimporteTotalChanged();
    partial void OnidVendedorChanging(int value);
    partial void OnidVendedorChanged();
    partial void OnidDespachoChanging(int value);
    partial void OnidDespachoChanged();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnestadoChanging(char value);
    partial void OnestadoChanged();
    partial void OncompAnteriorChanging(string value);
    partial void OncompAnteriorChanged();
    #endregion
		
		public Venta()
		{
			this._VentaDetalles = new EntitySet<VentaDetalle>(new Action<VentaDetalle>(this.attach_VentaDetalles), new Action<VentaDetalle>(this.detach_VentaDetalles));
			this._Persona = default(EntityRef<Persona>);
			this._Despacho = default(EntityRef<Despacho>);
			this._TipoComprobante = default(EntityRef<TipoComprobante>);
			this._Persona1 = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVenta", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long idVenta
		{
			get
			{
				return this._idVenta;
			}
			set
			{
				if ((this._idVenta != value))
				{
					this.OnidVentaChanging(value);
					this.SendPropertyChanging();
					this._idVenta = value;
					this.SendPropertyChanged("idVenta");
					this.OnidVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaVenta", DbType="Date NOT NULL")]
		public System.DateTime fechaVenta
		{
			get
			{
				return this._fechaVenta;
			}
			set
			{
				if ((this._fechaVenta != value))
				{
					this.OnfechaVentaChanging(value);
					this.SendPropertyChanging();
					this._fechaVenta = value;
					this.SendPropertyChanged("fechaVenta");
					this.OnfechaVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoComp", DbType="Int NOT NULL")]
		public int idTipoComp
		{
			get
			{
				return this._idTipoComp;
			}
			set
			{
				if ((this._idTipoComp != value))
				{
					if (this._TipoComprobante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoCompChanging(value);
					this.SendPropertyChanging();
					this._idTipoComp = value;
					this.SendPropertyChanged("idTipoComp");
					this.OnidTipoCompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comprobante", DbType="NVarChar(13)")]
		public string comprobante
		{
			get
			{
				return this._comprobante;
			}
			set
			{
				if ((this._comprobante != value))
				{
					this.OncomprobanteChanging(value);
					this.SendPropertyChanging();
					this._comprobante = value;
					this.SendPropertyChanged("comprobante");
					this.OncomprobanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL")]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidClienteChanging(value);
					this.SendPropertyChanging();
					this._idCliente = value;
					this.SendPropertyChanged("idCliente");
					this.OnidClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_importeTotal", DbType="Decimal(10,2) NOT NULL")]
		public decimal importeTotal
		{
			get
			{
				return this._importeTotal;
			}
			set
			{
				if ((this._importeTotal != value))
				{
					this.OnimporteTotalChanging(value);
					this.SendPropertyChanging();
					this._importeTotal = value;
					this.SendPropertyChanged("importeTotal");
					this.OnimporteTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVendedor", DbType="Int NOT NULL")]
		public int idVendedor
		{
			get
			{
				return this._idVendedor;
			}
			set
			{
				if ((this._idVendedor != value))
				{
					if (this._Persona1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidVendedorChanging(value);
					this.SendPropertyChanging();
					this._idVendedor = value;
					this.SendPropertyChanged("idVendedor");
					this.OnidVendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDespacho", DbType="Int NOT NULL")]
		public int idDespacho
		{
			get
			{
				return this._idDespacho;
			}
			set
			{
				if ((this._idDespacho != value))
				{
					if (this._Despacho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDespachoChanging(value);
					this.SendPropertyChanging();
					this._idDespacho = value;
					this.SendPropertyChanged("idDespacho");
					this.OnidDespachoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(1) NOT NULL")]
		public char estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compAnterior", DbType="NVarChar(13)")]
		public string compAnterior
		{
			get
			{
				return this._compAnterior;
			}
			set
			{
				if ((this._compAnterior != value))
				{
					this.OncompAnteriorChanging(value);
					this.SendPropertyChanging();
					this._compAnterior = value;
					this.SendPropertyChanged("compAnterior");
					this.OncompAnteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venta_VentaDetalle", Storage="_VentaDetalles", ThisKey="idVenta", OtherKey="idVenta")]
		public EntitySet<VentaDetalle> VentaDetalles
		{
			get
			{
				return this._VentaDetalles;
			}
			set
			{
				this._VentaDetalles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Venta", Storage="_Persona", ThisKey="idCliente", OtherKey="idPersona", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Ventas.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Ventas.Add(this);
						this._idCliente = value.idPersona;
					}
					else
					{
						this._idCliente = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Despacho_Venta", Storage="_Despacho", ThisKey="idDespacho", OtherKey="idDespacho", IsForeignKey=true)]
		public Despacho Despacho
		{
			get
			{
				return this._Despacho.Entity;
			}
			set
			{
				Despacho previousValue = this._Despacho.Entity;
				if (((previousValue != value) 
							|| (this._Despacho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Despacho.Entity = null;
						previousValue.Ventas.Remove(this);
					}
					this._Despacho.Entity = value;
					if ((value != null))
					{
						value.Ventas.Add(this);
						this._idDespacho = value.idDespacho;
					}
					else
					{
						this._idDespacho = default(int);
					}
					this.SendPropertyChanged("Despacho");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoComprobante_Venta", Storage="_TipoComprobante", ThisKey="idTipoComp", OtherKey="idTipoComp", IsForeignKey=true)]
		public TipoComprobante TipoComprobante
		{
			get
			{
				return this._TipoComprobante.Entity;
			}
			set
			{
				TipoComprobante previousValue = this._TipoComprobante.Entity;
				if (((previousValue != value) 
							|| (this._TipoComprobante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoComprobante.Entity = null;
						previousValue.Ventas.Remove(this);
					}
					this._TipoComprobante.Entity = value;
					if ((value != null))
					{
						value.Ventas.Add(this);
						this._idTipoComp = value.idTipoComp;
					}
					else
					{
						this._idTipoComp = default(int);
					}
					this.SendPropertyChanged("TipoComprobante");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Venta1", Storage="_Persona1", ThisKey="idVendedor", OtherKey="idPersona", IsForeignKey=true)]
		public Persona Persona1
		{
			get
			{
				return this._Persona1.Entity;
			}
			set
			{
				Persona previousValue = this._Persona1.Entity;
				if (((previousValue != value) 
							|| (this._Persona1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona1.Entity = null;
						previousValue.Ventas1.Remove(this);
					}
					this._Persona1.Entity = value;
					if ((value != null))
					{
						value.Ventas1.Add(this);
						this._idVendedor = value.idPersona;
					}
					else
					{
						this._idVendedor = default(int);
					}
					this.SendPropertyChanged("Persona1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VentaDetalles(VentaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.Venta = this;
		}
		
		private void detach_VentaDetalles(VentaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.Venta = null;
		}
	}
}
#pragma warning restore 1591
